### PR TITLE
opinion: need your comment/guidiance on my fix

### PR DESCRIPTION
**Pull request by MegaWale**
i tackled the title issue first.

i added a set_title method to the widget.py/TempyPage

Will love to know if i am on the right track. Need your guidiance.

### CODE REVIEW

**Comment by Hrabal** [comment]
Hey, yes it's good to have a separate method to call in __init__ . Just add a couple of tests for the new method.

**Comment by MegaWale** [comment]
okay...:+1:

**Comment by MegaWale** [comment]
hey @Hrabal, after adding a test, i ran the command
`~python test_widgets.py`
to check, hope i am doing anything wrong.
but i got an error:
`Traceback (most recent call last):
  File "test_widgets.py", line 8, in <module>
    from tempy.widgets import TempyTable, TempyList, TempyPage
ImportError: No module named 'tempy'`

also, what do you suggest i do with the failing checks??
thanks

**Comment by Hrabal** [comment]
To run the tests go to the base repository folder and run "python3 -m unittest discover". This way the test framework will run all the tests in the project. (See https://docs.python.org/3.6/library/unittest.html for more info). Regarding the failing test you can see in the TravisCI page the error traceback..

**Comment by MegaWale** [comment]
ran the test and it passed. thanks for the link, learn't something new. And all the checks passed!
what do you think?

**Comment by Hrabal** [comment]
Good! Now your new method can be used, alongside set_doctype, inside the TempyPage.__init__ so the issue is solved.

**Comment by MegaWale** [comment]
good to know that @Hrabal, thanks.

**Pull request merged**
