### PR TITLE
Added navigational links to / 

### PR DESCRIPTION
**Pull request by Chiouonthis**
Now users can more easily see all current examples instead of having to remember what the other paths were and typing in each endpoint manually.

### CODE REVIEW

**Comment by Chiouonthis** [comment]
I've also created a homepage.py that leverages TemPy to do the same thing, if we would prefer to use that instead of HTML tags for navigation. Please let me know if you'd rather me commit and submit a pull request for something like that.

**Comment by Hrabal** [comment]
Hi @Chiouonthis, I never had time to really work on the examples but yes, ideally every page in this microsite is served using TemPy. If you are willing to redo the home handler with TemPy I'll close this PR.

Also, I wrote those examples some TemPy versions ago, so if you find something broken or with a weird output please let me know!

**Comment by Chiouonthis** [comment]
> Hi @Chiouonthis, I never had time to really work on the examples but yes, ideally every page in this microsite is served using TemPy. If you are willing to redo the home handler with TemPy I'll close this PR.
> 

Sure thing, I can submit a new PR with the TemPy version. 

> Also, I wrote those examples some TemPy versions ago, so if you find something broken or with a weird output please let me know!

I noticed a few odd renderings; I will report them as separate issues when I get a chance to look at them again and if it seems necessary. Thanks!

**Comment by Hrabal** [comment]
Thanks!

**Pull request closed without merging**
